import { readFileSync } from "node:fs";
import { chromium } from "playwright";
import { setTimeout as sleep } from "node:timers/promises";
import { buildMinecraftGLB } from "../packages/mcmodel/dist/index.js";
const items=[["klee立绘","/tmp/skinmint-bench/klee.png","30eba45d-c03b-4697-8d06-63e1f943614d"],["keqing立绘","/tmp/skinmint-bench/keqing.png","1a413cf6-681d-4f43-ad2d-dd170d586432"],["cyberpunk立绘","/tmp/skinmint-shots/p1-portrait.png","4129638a-8503-49e9-b376-d86a8f1f4222"]];
const cells=[];for(const [name,pp,id] of items){const portrait=readFileSync(pp).toString("base64");const skin=readFileSync(`/tmp/skin-lib/${id}.png`);const glb=Buffer.from(await buildMinecraftGLB(new Uint8Array(skin),{overlay:true})).toString("base64");cells.push({name,portrait,skin:skin.toString("base64"),glb});}
const HTML=`<!DOCTYPE html><html><head><meta charset=utf-8><style>html,body{margin:0;background:#f1ead9;font-family:monospace}.row{display:flex;align-items:center;gap:10px;border-bottom:1px solid #ccc;padding:8px}img{height:260px;border:1px solid #999;border-radius:8px}img.sk{height:128px;image-rendering:pixelated}.lbl{width:90px;font-weight:700}.vp{width:260px;height:320px}</style><script type=importmap>{"imports":{"three":"https://cdn.jsdelivr.net/npm/three@0.169.0/build/three.module.js","three/addons/":"https://cdn.jsdelivr.net/npm/three@0.169.0/examples/jsm/"}}</script></head><body>
${cells.map(c=>`<div class=row><span class=lbl>${c.name}</span><img src="data:image/png;base64,${c.portrait}"><img class=sk src="data:image/png;base64,${c.skin}"><div class=vp data-glb="${c.glb}"></div></div>`).join("")}
<script type=module>import * as THREE from "three";import {GLTFLoader} from "three/addons/loaders/GLTFLoader.js";for(const el of document.querySelectorAll(".vp")){const w=el.clientWidth,h=el.clientHeight;const sc=new THREE.Scene();const r=new THREE.WebGLRenderer({antialias:true,alpha:true,preserveDrawingBuffer:true});r.setPixelRatio(2);r.setSize(w,h);const cam=new THREE.PerspectiveCamera(28,w/h,.1,100);cam.position.set(2.2,1.1,4.6);cam.lookAt(0,1.05,0);await new Promise(d=>{new GLTFLoader().load("data:model/gltf-binary;base64,"+el.dataset.glb,g=>{sc.add(g.scene);r.render(sc,cam);const im=new Image();im.width=w;im.height=h;im.src=r.domElement.toDataURL();el.replaceWith(im);r.dispose();r.forceContextLoss();d();},undefined,()=>d())});}window.__done=1;</script></body></html>`;
const b=await chromium.launch({args:["--use-gl=angle","--use-angle=swiftshader","--enable-unsafe-swiftshader","--ignore-gpu-blocklist"]});const p=await b.newPage({viewport:{width:720,height:1050},deviceScaleFactor:1.4});await p.setContent(HTML,{waitUntil:"networkidle"});await p.waitForFunction("window.__done===1",{timeout:20000}).catch(()=>{});await sleep(700);await p.screenshot({path:"/tmp/skinmint-shots/retrieve-big.png",fullPage:true});await b.close();console.log("ok");
