import { chromium } from "playwright";
import { setTimeout as sleep } from "node:timers/promises";
const browser = await chromium.launch({ args: ["--use-gl=angle","--use-angle=swiftshader","--enable-unsafe-swiftshader","--ignore-gpu-blocklist"] });
const page = await browser.newPage({ viewport: { width: 700, height: 600 }, deviceScaleFactor: 2 });
const errs = []; page.on("pageerror", e=>errs.push(String(e))); page.on("console", m=>m.type()==="error"&&errs.push(m.text()));
await page.goto(process.env.URL, { waitUntil: "networkidle" });
await sleep(6000);
await page.screenshot({ path: "/tmp/skinmint-shots/embed-smoke.png" });
await browser.close();
console.log("errors:", errs.length?errs:"none");
