import { chromium } from "playwright";
import { setTimeout as sleep } from "node:timers/promises";
const browser = await chromium.launch({ args: ["--use-gl=angle","--use-angle=swiftshader","--enable-unsafe-swiftshader","--ignore-gpu-blocklist"] });
const page = await browser.newPage({ viewport: { width: 1180, height: 820 }, deviceScaleFactor: 1 });
const errs=[]; page.on("pageerror",e=>errs.push(String(e)));
await page.goto("http://localhost:3000/", { waitUntil: "networkidle" });
await sleep(1200);
await page.locator('.composer-inner input').type("一只戴帽子的柴犬");
await sleep(400);
await page.screenshot({ path: "/tmp/skinmint-shots/hero-final.png" });
console.log("done; errors:", errs.slice(0,4));
await browser.close();
