import { chromium } from "playwright";
import { setTimeout as sleep } from "node:timers/promises";
const browser = await chromium.launch({ args: ["--use-gl=angle","--use-angle=swiftshader","--enable-unsafe-swiftshader","--ignore-gpu-blocklist"] });
const page = await browser.newPage({ viewport: { width: 1100, height: 820 }, deviceScaleFactor: 2 });
const msgs = [];
page.on("console", (m) => msgs.push(`[${m.type()}] ${m.text()}`));
page.on("pageerror", (e) => msgs.push(`[pageerror] ${String(e)}`));
page.on("requestfailed", (r) => msgs.push(`[reqfail] ${r.url()} ${r.failure()?.errorText}`));
await page.goto("http://localhost:3000/", { waitUntil: "networkidle" });
await page.getByRole("textbox").last().fill(process.env.GLB_URL);
await sleep(13000);
await page.screenshot({ path: "/tmp/skinmint-shots/debug-render.png" });
await browser.close();
console.log(msgs.join("\n"));
