import { chromium } from "playwright";
import { setTimeout as sleep } from "node:timers/promises";
const browser = await chromium.launch({ args: ["--use-gl=angle","--use-angle=swiftshader","--enable-unsafe-swiftshader","--ignore-gpu-blocklist"] });
const page = await browser.newPage({ viewport: { width: 1280, height: 860 }, deviceScaleFactor: 1 });
const errs=[]; page.on("pageerror",e=>errs.push(String(e))); page.on("console",m=>m.type()==="error"&&errs.push(m.text()));
await page.goto("http://localhost:3000/", { waitUntil: "networkidle" });
await sleep(1500);
await page.screenshot({ path: "/tmp/skinmint-shots/studio-1-empty.png" });
console.log("done; errors:", errs.filter(e=>!e.includes("_next")).slice(0,5));
await browser.close();
